
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mountainspoem.init;

import net.mcreator.mountainspoem.block.ZunbottleBlock;
import net.mcreator.mountainspoem.block.ZhuyuGrassBlock;
import net.mcreator.mountainspoem.block.YingYangFlowerBlock;
import net.mcreator.mountainspoem.block.YellowLanternBlock;
import net.mcreator.mountainspoem.block.YanwoodBlock;
import net.mcreator.mountainspoem.block.YanlogBlock;
import net.mcreator.mountainspoem.block.YanleavesBlock;
import net.mcreator.mountainspoem.block.YanTrapdoorBlock;
import net.mcreator.mountainspoem.block.YanStairsBlock;
import net.mcreator.mountainspoem.block.YanSlabBlock;
import net.mcreator.mountainspoem.block.YanPressurePlateBlock;
import net.mcreator.mountainspoem.block.YanPlanksBlock;
import net.mcreator.mountainspoem.block.YanFenceGateBlock;
import net.mcreator.mountainspoem.block.YanFenceBlock;
import net.mcreator.mountainspoem.block.YanDoorBlock;
import net.mcreator.mountainspoem.block.YanButtonBlock;
import net.mcreator.mountainspoem.block.XunyearBlock;
import net.mcreator.mountainspoem.block.XunLeavesBerryBlock;
import net.mcreator.mountainspoem.block.WutiaoGrassBlock;
import net.mcreator.mountainspoem.block.WutiaoFlowerBlock;
import net.mcreator.mountainspoem.block.WhiteLanternBlock;
import net.mcreator.mountainspoem.block.WhiteJianGrassMatCoveredSacrificialTableBlock;
import net.mcreator.mountainspoem.block.WhiteJianGrassMatBlock;
import net.mcreator.mountainspoem.block.WhiteJianGrassBlockBlock;
import net.mcreator.mountainspoem.block.WhiteJianGrassBlock;
import net.mcreator.mountainspoem.block.UnderRockWallBlock;
import net.mcreator.mountainspoem.block.UnderRockStairsBlock;
import net.mcreator.mountainspoem.block.UnderRockSlabsBlock;
import net.mcreator.mountainspoem.block.UnderRockQuartzOreBlock;
import net.mcreator.mountainspoem.block.UnderRockGoldOreBlock;
import net.mcreator.mountainspoem.block.UnderRockFenceBlock;
import net.mcreator.mountainspoem.block.UnderRockBricksBlock;
import net.mcreator.mountainspoem.block.UnderRockBrickWallBlock;
import net.mcreator.mountainspoem.block.UnderRockBrickStairsBlock;
import net.mcreator.mountainspoem.block.UnderRockBrickSlabBlock;
import net.mcreator.mountainspoem.block.UnderRockBrickFenceBlock;
import net.mcreator.mountainspoem.block.UnderRockBlock;
import net.mcreator.mountainspoem.block.UnderOrchidBlock;
import net.mcreator.mountainspoem.block.UnderIronOreBlock;
import net.mcreator.mountainspoem.block.UnderIronBlockBlock;
import net.mcreator.mountainspoem.block.UnderGrassBlockBlock;
import net.mcreator.mountainspoem.block.UnderGrassBlock;
import net.mcreator.mountainspoem.block.UnderFlowerBlock;
import net.mcreator.mountainspoem.block.UnderDirtBlock;
import net.mcreator.mountainspoem.block.TingZhuBlock;
import net.mcreator.mountainspoem.block.TheUnderPortalBlock;
import net.mcreator.mountainspoem.block.TheBloodCopperBlockBlock;
import net.mcreator.mountainspoem.block.StrippedYanWoodBlock;
import net.mcreator.mountainspoem.block.StrippedYanLogBlock;
import net.mcreator.mountainspoem.block.StrippedShatangLogBlock;
import net.mcreator.mountainspoem.block.StrippedShaTangWoodBlock;
import net.mcreator.mountainspoem.block.StrippedPeachBlossomWoodBlock;
import net.mcreator.mountainspoem.block.StrippedPeachBlossomLogBlock;
import net.mcreator.mountainspoem.block.StrippedPanWoodBlock;
import net.mcreator.mountainspoem.block.StrippedPanLogBlock;
import net.mcreator.mountainspoem.block.StrippedNewjiangWoodBlock;
import net.mcreator.mountainspoem.block.StrippedNewjiangLogBlock;
import net.mcreator.mountainspoem.block.StrippedHuangGuanWoodBlock;
import net.mcreator.mountainspoem.block.StrippedHuangGuanLogBlock;
import net.mcreator.mountainspoem.block.SpookyBronzeDevourerStatueBlock;
import net.mcreator.mountainspoem.block.ShatangWoodBlock;
import net.mcreator.mountainspoem.block.ShatangTrapdoorBlock;
import net.mcreator.mountainspoem.block.ShatangStairsBlock;
import net.mcreator.mountainspoem.block.ShatangSlabBlock;
import net.mcreator.mountainspoem.block.ShatangPressurePlateBlock;
import net.mcreator.mountainspoem.block.ShatangPlanksBlock;
import net.mcreator.mountainspoem.block.ShatangLogBlock;
import net.mcreator.mountainspoem.block.ShatangLeavesBlock;
import net.mcreator.mountainspoem.block.ShatangFenceGateBlock;
import net.mcreator.mountainspoem.block.ShatangFenceBlock;
import net.mcreator.mountainspoem.block.ShatangDoorBlock;
import net.mcreator.mountainspoem.block.ShatangButtonBlock;
import net.mcreator.mountainspoem.block.ScarletThornsBlock;
import net.mcreator.mountainspoem.block.SanguineSoilBlock;
import net.mcreator.mountainspoem.block.SanguineSandBlock;
import net.mcreator.mountainspoem.block.SanguineGrassBlock;
import net.mcreator.mountainspoem.block.SanguineGlassBlock;
import net.mcreator.mountainspoem.block.SanguineFlowerBlock;
import net.mcreator.mountainspoem.block.SanguineCactusBlock;
import net.mcreator.mountainspoem.block.SaltBlcokBlock;
import net.mcreator.mountainspoem.block.SalineOreBlock;
import net.mcreator.mountainspoem.block.SacrificialTableBlock;
import net.mcreator.mountainspoem.block.RongGrassBlock;
import net.mcreator.mountainspoem.block.RedLanternBlock;
import net.mcreator.mountainspoem.block.PurpleLanternBlock;
import net.mcreator.mountainspoem.block.PinkLanternBlock;
import net.mcreator.mountainspoem.block.PeachBlossomWoodBlock;
import net.mcreator.mountainspoem.block.PeachBlossomTrapdoorBlock;
import net.mcreator.mountainspoem.block.PeachBlossomStairsBlock;
import net.mcreator.mountainspoem.block.PeachBlossomSlabBlock;
import net.mcreator.mountainspoem.block.PeachBlossomPressurePlateBlock;
import net.mcreator.mountainspoem.block.PeachBlossomPlanksBlock;
import net.mcreator.mountainspoem.block.PeachBlossomLogBlock;
import net.mcreator.mountainspoem.block.PeachBlossomLeavesBlock;
import net.mcreator.mountainspoem.block.PeachBlossomFenceGateBlock;
import net.mcreator.mountainspoem.block.PeachBlossomFenceBlock;
import net.mcreator.mountainspoem.block.PeachBlossomDoorBlock;
import net.mcreator.mountainspoem.block.PeachBlossomButtonBlock;
import net.mcreator.mountainspoem.block.PapermakingBoardBlock;
import net.mcreator.mountainspoem.block.PanWoodBlock;
import net.mcreator.mountainspoem.block.PanTrapdoorBlock;
import net.mcreator.mountainspoem.block.PanStairsBlock;
import net.mcreator.mountainspoem.block.PanSlabBlock;
import net.mcreator.mountainspoem.block.PanPressurePlateBlock;
import net.mcreator.mountainspoem.block.PanPlanksBlock;
import net.mcreator.mountainspoem.block.PanLogBlock;
import net.mcreator.mountainspoem.block.PanLeavesBlock;
import net.mcreator.mountainspoem.block.PanFenceGateBlock;
import net.mcreator.mountainspoem.block.PanFenceBlock;
import net.mcreator.mountainspoem.block.PanDoorBlock;
import net.mcreator.mountainspoem.block.PanButtonBlock;
import net.mcreator.mountainspoem.block.OrangeLanternBlock;
import net.mcreator.mountainspoem.block.NewjianglogBlock;
import net.mcreator.mountainspoem.block.NewjiangleaveBlock;
import net.mcreator.mountainspoem.block.NewjiangWoodBlock;
import net.mcreator.mountainspoem.block.NewjiangTrapdoorBlock;
import net.mcreator.mountainspoem.block.NewjiangStairsBlock;
import net.mcreator.mountainspoem.block.NewjiangSlabBlock;
import net.mcreator.mountainspoem.block.NewjiangPressurePlateBlock;
import net.mcreator.mountainspoem.block.NewjiangPlanksBlock;
import net.mcreator.mountainspoem.block.NewjiangFenceGateBlock;
import net.mcreator.mountainspoem.block.NewjiangFenceBlock;
import net.mcreator.mountainspoem.block.NewjiangDoorBlock;
import net.mcreator.mountainspoem.block.NewjiangButtonBlock;
import net.mcreator.mountainspoem.block.ManufacturingblockBlock;
import net.mcreator.mountainspoem.block.MagentaLanternBlock;
import net.mcreator.mountainspoem.block.LushGrassBlockBlock;
import net.mcreator.mountainspoem.block.LushDirtBlock;
import net.mcreator.mountainspoem.block.LimeLanternBlock;
import net.mcreator.mountainspoem.block.LightGrayLanternBlock;
import net.mcreator.mountainspoem.block.LightBlueLanternBlock;
import net.mcreator.mountainspoem.block.JianmeibambooBlock;
import net.mcreator.mountainspoem.block.JadeOreBlock;
import net.mcreator.mountainspoem.block.JadeCongBlock;
import net.mcreator.mountainspoem.block.JadeCarverBlock;
import net.mcreator.mountainspoem.block.JadeBlockBlock;
import net.mcreator.mountainspoem.block.HuangGuanWoodBlock;
import net.mcreator.mountainspoem.block.HuangGuanTrapdoorBlock;
import net.mcreator.mountainspoem.block.HuangGuanStairsBlock;
import net.mcreator.mountainspoem.block.HuangGuanSlabBlock;
import net.mcreator.mountainspoem.block.HuangGuanPressurePlateBlock;
import net.mcreator.mountainspoem.block.HuangGuanPlanksBlock;
import net.mcreator.mountainspoem.block.HuangGuanLogBlock;
import net.mcreator.mountainspoem.block.HuangGuanLeavesBlock;
import net.mcreator.mountainspoem.block.HuangGuanFenceGateBlock;
import net.mcreator.mountainspoem.block.HuangGuanFenceBlock;
import net.mcreator.mountainspoem.block.HuangGuanDoorBlock;
import net.mcreator.mountainspoem.block.HuangGuanButtonBlock;
import net.mcreator.mountainspoem.block.HollowMudBricksBlock;
import net.mcreator.mountainspoem.block.GuiBasketBlock;
import net.mcreator.mountainspoem.block.GreenRockBlock;
import net.mcreator.mountainspoem.block.GreenLanternBlock;
import net.mcreator.mountainspoem.block.GreenJadeButtonBlock;
import net.mcreator.mountainspoem.block.GreenJadeBlockBlock;
import net.mcreator.mountainspoem.block.GrayLanternBlock;
import net.mcreator.mountainspoem.block.FruitfulYanLeavesBlock;
import net.mcreator.mountainspoem.block.FruitfulShatangLeavesBlock;
import net.mcreator.mountainspoem.block.DryingBoardBlock;
import net.mcreator.mountainspoem.block.DirtWithRongGrassTubersBlock;
import net.mcreator.mountainspoem.block.DeepslateJadeOreBlock;
import net.mcreator.mountainspoem.block.DeepslateCarnelianOreBlock;
import net.mcreator.mountainspoem.block.DeepslateBloodCopperOreBlock;
import net.mcreator.mountainspoem.block.DarkSpruceLogBlock;
import net.mcreator.mountainspoem.block.CyanLanternBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleZhiBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleZhengBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleSouthMountainsGodBlock;
import net.mcreator.mountainspoem.block.CopperZunBottlePiglinBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleLongChiBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleLeiBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleEnderDragonBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleChickenBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleChangfuBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleBoshiBlock;
import net.mcreator.mountainspoem.block.CopperZunBottleBlock;
import net.mcreator.mountainspoem.block.CopperSmallDingBlock;
import net.mcreator.mountainspoem.block.CopperGuiBlock;
import net.mcreator.mountainspoem.block.CopperDouLeiMeatSauceBlock;
import net.mcreator.mountainspoem.block.CopperDouChangfuChickenSauceBlock;
import net.mcreator.mountainspoem.block.CopperDouBoyiMeatSauceBlock;
import net.mcreator.mountainspoem.block.CopperDouBlock;
import net.mcreator.mountainspoem.block.CobbledGreenRockBlock;
import net.mcreator.mountainspoem.block.CoarseSaltBlockBlock;
import net.mcreator.mountainspoem.block.CarnelianOreBlock;
import net.mcreator.mountainspoem.block.CarnelianBlockBlock;
import net.mcreator.mountainspoem.block.BrownLanternBlock;
import net.mcreator.mountainspoem.block.BronzeXuanBlock;
import net.mcreator.mountainspoem.block.BronzeJugBlock;
import net.mcreator.mountainspoem.block.BronzeDevourerStatueBlock;
import net.mcreator.mountainspoem.block.BlueLanternBlock;
import net.mcreator.mountainspoem.block.BloodthirstyThornsBlock;
import net.mcreator.mountainspoem.block.BloodthirstyChrysanthemumBlock;
import net.mcreator.mountainspoem.block.BloodcopperoreBlock;
import net.mcreator.mountainspoem.block.BlackLanternBlock;
import net.mcreator.mountainspoem.block.AlgaeJadeBlockBlock;
import net.mcreator.mountainspoem.MountainsPoemMod;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class MountainsPoemModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, MountainsPoemMod.MODID);
	public static final RegistryObject<Block> JIANMEIBAMBOO = REGISTRY.register("jianmeibamboo", () -> new JianmeibambooBlock());
	public static final RegistryObject<Block> YANLOG = REGISTRY.register("yanlog", () -> new YanlogBlock());
	public static final RegistryObject<Block> YANLEAVES = REGISTRY.register("yanleaves", () -> new YanleavesBlock());
	public static final RegistryObject<Block> ZUNBOTTLE = REGISTRY.register("zunbottle", () -> new ZunbottleBlock());
	public static final RegistryObject<Block> XUN_LEAVES = REGISTRY.register("xun_leaves", () -> new XunyearBlock());
	public static final RegistryObject<Block> GILDED_COPPER_BLOCK = REGISTRY.register("gilded_copper_block", () -> new ManufacturingblockBlock());
	public static final RegistryObject<Block> NEWJIANGLOG = REGISTRY.register("newjianglog", () -> new NewjianglogBlock());
	public static final RegistryObject<Block> NEWJIANGLEAVE = REGISTRY.register("newjiangleave", () -> new NewjiangleaveBlock());
	public static final RegistryObject<Block> BLOODCOPPERORE = REGISTRY.register("bloodcopperore", () -> new BloodcopperoreBlock());
	public static final RegistryObject<Block> YAN_PLANKS = REGISTRY.register("yan_planks", () -> new YanPlanksBlock());
	public static final RegistryObject<Block> YAN_STAIRS = REGISTRY.register("yan_stairs", () -> new YanStairsBlock());
	public static final RegistryObject<Block> YAN_SLAB = REGISTRY.register("yan_slab", () -> new YanSlabBlock());
	public static final RegistryObject<Block> YAN_FENCE = REGISTRY.register("yan_fence", () -> new YanFenceBlock());
	public static final RegistryObject<Block> YAN_FENCE_GATE = REGISTRY.register("yan_fence_gate", () -> new YanFenceGateBlock());
	public static final RegistryObject<Block> YAN_PRESSURE_PLATE = REGISTRY.register("yan_pressure_plate", () -> new YanPressurePlateBlock());
	public static final RegistryObject<Block> YAN_BUTTON = REGISTRY.register("yan_button", () -> new YanButtonBlock());
	public static final RegistryObject<Block> YANWOOD = REGISTRY.register("yanwood", () -> new YanwoodBlock());
	public static final RegistryObject<Block> NEWJIANG_PLANKS = REGISTRY.register("newjiang_planks", () -> new NewjiangPlanksBlock());
	public static final RegistryObject<Block> NEWJIANG_STAIRS = REGISTRY.register("newjiang_stairs", () -> new NewjiangStairsBlock());
	public static final RegistryObject<Block> NEWJIANG_SLAB = REGISTRY.register("newjiang_slab", () -> new NewjiangSlabBlock());
	public static final RegistryObject<Block> NEWJIANG_FENCE = REGISTRY.register("newjiang_fence", () -> new NewjiangFenceBlock());
	public static final RegistryObject<Block> NEWJIANG_FENCE_GATE = REGISTRY.register("newjiang_fence_gate", () -> new NewjiangFenceGateBlock());
	public static final RegistryObject<Block> NEWJIANG_PRESSURE_PLATE = REGISTRY.register("newjiang_pressure_plate", () -> new NewjiangPressurePlateBlock());
	public static final RegistryObject<Block> NEWJIANG_BUTTON = REGISTRY.register("newjiang_button", () -> new NewjiangButtonBlock());
	public static final RegistryObject<Block> JADE_ORE = REGISTRY.register("jade_ore", () -> new JadeOreBlock());
	public static final RegistryObject<Block> NEWJIANG_WOOD = REGISTRY.register("newjiang_wood", () -> new NewjiangWoodBlock());
	public static final RegistryObject<Block> HUANG_GUAN_WOOD = REGISTRY.register("huang_guan_wood", () -> new HuangGuanWoodBlock());
	public static final RegistryObject<Block> HUANG_GUAN_LOG = REGISTRY.register("huang_guan_log", () -> new HuangGuanLogBlock());
	public static final RegistryObject<Block> HUANG_GUAN_PLANKS = REGISTRY.register("huang_guan_planks", () -> new HuangGuanPlanksBlock());
	public static final RegistryObject<Block> HUANG_GUAN_LEAVES = REGISTRY.register("huang_guan_leaves", () -> new HuangGuanLeavesBlock());
	public static final RegistryObject<Block> HUANG_GUAN_STAIRS = REGISTRY.register("huang_guan_stairs", () -> new HuangGuanStairsBlock());
	public static final RegistryObject<Block> HUANG_GUAN_SLAB = REGISTRY.register("huang_guan_slab", () -> new HuangGuanSlabBlock());
	public static final RegistryObject<Block> HUANG_GUAN_FENCE = REGISTRY.register("huang_guan_fence", () -> new HuangGuanFenceBlock());
	public static final RegistryObject<Block> HUANG_GUAN_FENCE_GATE = REGISTRY.register("huang_guan_fence_gate", () -> new HuangGuanFenceGateBlock());
	public static final RegistryObject<Block> HUANG_GUAN_PRESSURE_PLATE = REGISTRY.register("huang_guan_pressure_plate", () -> new HuangGuanPressurePlateBlock());
	public static final RegistryObject<Block> HUANG_GUAN_BUTTON = REGISTRY.register("huang_guan_button", () -> new HuangGuanButtonBlock());
	public static final RegistryObject<Block> SHATANG_WOOD = REGISTRY.register("shatang_wood", () -> new ShatangWoodBlock());
	public static final RegistryObject<Block> SHATANG_LOG = REGISTRY.register("shatang_log", () -> new ShatangLogBlock());
	public static final RegistryObject<Block> SHATANG_PLANKS = REGISTRY.register("shatang_planks", () -> new ShatangPlanksBlock());
	public static final RegistryObject<Block> SHATANG_LEAVES = REGISTRY.register("shatang_leaves", () -> new ShatangLeavesBlock());
	public static final RegistryObject<Block> SHATANG_STAIRS = REGISTRY.register("shatang_stairs", () -> new ShatangStairsBlock());
	public static final RegistryObject<Block> SHATANG_SLAB = REGISTRY.register("shatang_slab", () -> new ShatangSlabBlock());
	public static final RegistryObject<Block> SHATANG_FENCE = REGISTRY.register("shatang_fence", () -> new ShatangFenceBlock());
	public static final RegistryObject<Block> SHATANG_FENCE_GATE = REGISTRY.register("shatang_fence_gate", () -> new ShatangFenceGateBlock());
	public static final RegistryObject<Block> SHATANG_PRESSURE_PLATE = REGISTRY.register("shatang_pressure_plate", () -> new ShatangPressurePlateBlock());
	public static final RegistryObject<Block> SHATANG_BUTTON = REGISTRY.register("shatang_button", () -> new ShatangButtonBlock());
	public static final RegistryObject<Block> PAN_WOOD = REGISTRY.register("pan_wood", () -> new PanWoodBlock());
	public static final RegistryObject<Block> PAN_LOG = REGISTRY.register("pan_log", () -> new PanLogBlock());
	public static final RegistryObject<Block> PAN_PLANKS = REGISTRY.register("pan_planks", () -> new PanPlanksBlock());
	public static final RegistryObject<Block> PAN_LEAVES = REGISTRY.register("pan_leaves", () -> new PanLeavesBlock());
	public static final RegistryObject<Block> PAN_STAIRS = REGISTRY.register("pan_stairs", () -> new PanStairsBlock());
	public static final RegistryObject<Block> PAN_SLAB = REGISTRY.register("pan_slab", () -> new PanSlabBlock());
	public static final RegistryObject<Block> PAN_FENCE = REGISTRY.register("pan_fence", () -> new PanFenceBlock());
	public static final RegistryObject<Block> PAN_FENCE_GATE = REGISTRY.register("pan_fence_gate", () -> new PanFenceGateBlock());
	public static final RegistryObject<Block> PAN_PRESSURE_PLATE = REGISTRY.register("pan_pressure_plate", () -> new PanPressurePlateBlock());
	public static final RegistryObject<Block> PAN_BUTTON = REGISTRY.register("pan_button", () -> new PanButtonBlock());
	public static final RegistryObject<Block> DUHENG_FLOWER = REGISTRY.register("duheng_flower", () -> new WutiaoFlowerBlock());
	public static final RegistryObject<Block> ALGAE_JADE_BLOCK = REGISTRY.register("algae_jade_block", () -> new AlgaeJadeBlockBlock());
	public static final RegistryObject<Block> JADE_BLOCK = REGISTRY.register("jade_block", () -> new JadeBlockBlock());
	public static final RegistryObject<Block> GREEN_JADE_BUTTON = REGISTRY.register("green_jade_button", () -> new GreenJadeButtonBlock());
	public static final RegistryObject<Block> YAN_TRAPDOOR = REGISTRY.register("yan_trapdoor", () -> new YanTrapdoorBlock());
	public static final RegistryObject<Block> NEWJIANG_TRAPDOOR = REGISTRY.register("newjiang_trapdoor", () -> new NewjiangTrapdoorBlock());
	public static final RegistryObject<Block> NEWJIANG_DOOR = REGISTRY.register("newjiang_door", () -> new NewjiangDoorBlock());
	public static final RegistryObject<Block> YAN_DOOR = REGISTRY.register("yan_door", () -> new YanDoorBlock());
	public static final RegistryObject<Block> SHATANG_TRAPDOOR = REGISTRY.register("shatang_trapdoor", () -> new ShatangTrapdoorBlock());
	public static final RegistryObject<Block> SHATANG_DOOR = REGISTRY.register("shatang_door", () -> new ShatangDoorBlock());
	public static final RegistryObject<Block> PAN_TRAPDOOR = REGISTRY.register("pan_trapdoor", () -> new PanTrapdoorBlock());
	public static final RegistryObject<Block> PAN_DOOR = REGISTRY.register("pan_door", () -> new PanDoorBlock());
	public static final RegistryObject<Block> HUANG_GUAN_TRAPDOOR = REGISTRY.register("huang_guan_trapdoor", () -> new HuangGuanTrapdoorBlock());
	public static final RegistryObject<Block> HUANG_GUAN_DOOR = REGISTRY.register("huang_guan_door", () -> new HuangGuanDoorBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_WOOD = REGISTRY.register("peach_blossom_wood", () -> new PeachBlossomWoodBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_LOG = REGISTRY.register("peach_blossom_log", () -> new PeachBlossomLogBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_PLANKS = REGISTRY.register("peach_blossom_planks", () -> new PeachBlossomPlanksBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_LEAVES = REGISTRY.register("peach_blossom_leaves", () -> new PeachBlossomLeavesBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_STAIRS = REGISTRY.register("peach_blossom_stairs", () -> new PeachBlossomStairsBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_SLAB = REGISTRY.register("peach_blossom_slab", () -> new PeachBlossomSlabBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_FENCE = REGISTRY.register("peach_blossom_fence", () -> new PeachBlossomFenceBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_FENCE_GATE = REGISTRY.register("peach_blossom_fence_gate", () -> new PeachBlossomFenceGateBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_PRESSURE_PLATE = REGISTRY.register("peach_blossom_pressure_plate", () -> new PeachBlossomPressurePlateBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_BUTTON = REGISTRY.register("peach_blossom_button", () -> new PeachBlossomButtonBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_DOOR = REGISTRY.register("peach_blossom_door", () -> new PeachBlossomDoorBlock());
	public static final RegistryObject<Block> PEACH_BLOSSOM_TRAPDOOR = REGISTRY.register("peach_blossom_trapdoor", () -> new PeachBlossomTrapdoorBlock());
	public static final RegistryObject<Block> LUSH_DIRT = REGISTRY.register("lush_dirt", () -> new LushDirtBlock());
	public static final RegistryObject<Block> LUSH_GRASS_BLOCK = REGISTRY.register("lush_grass_block", () -> new LushGrassBlockBlock());
	public static final RegistryObject<Block> DARK_SPRUCE_LOG = REGISTRY.register("dark_spruce_log", () -> new DarkSpruceLogBlock());
	public static final RegistryObject<Block> STRIPPED_YAN_LOG = REGISTRY.register("stripped_yan_log", () -> new StrippedYanLogBlock());
	public static final RegistryObject<Block> STRIPPED_HUANG_GUAN_LOG = REGISTRY.register("stripped_huang_guan_log", () -> new StrippedHuangGuanLogBlock());
	public static final RegistryObject<Block> STRIPPED_SHATANG_LOG = REGISTRY.register("stripped_shatang_log", () -> new StrippedShatangLogBlock());
	public static final RegistryObject<Block> STRIPPED_NEWJIANG_LOG = REGISTRY.register("stripped_newjiang_log", () -> new StrippedNewjiangLogBlock());
	public static final RegistryObject<Block> STRIPPED_PAN_LOG = REGISTRY.register("stripped_pan_log", () -> new StrippedPanLogBlock());
	public static final RegistryObject<Block> STRIPPED_PEACH_BLOSSOM_LOG = REGISTRY.register("stripped_peach_blossom_log", () -> new StrippedPeachBlossomLogBlock());
	public static final RegistryObject<Block> STRIPPED_YAN_WOOD = REGISTRY.register("stripped_yan_wood", () -> new StrippedYanWoodBlock());
	public static final RegistryObject<Block> STRIPPED_HUANG_GUAN_WOOD = REGISTRY.register("stripped_huang_guan_wood", () -> new StrippedHuangGuanWoodBlock());
	public static final RegistryObject<Block> STRIPPED_NEWJIANG_WOOD = REGISTRY.register("stripped_newjiang_wood", () -> new StrippedNewjiangWoodBlock());
	public static final RegistryObject<Block> STRIPPED_SHA_TANG_WOOD = REGISTRY.register("stripped_sha_tang_wood", () -> new StrippedShaTangWoodBlock());
	public static final RegistryObject<Block> STRIPPED_PAN_WOOD = REGISTRY.register("stripped_pan_wood", () -> new StrippedPanWoodBlock());
	public static final RegistryObject<Block> STRIPPED_PEACH_BLOSSOM_WOOD = REGISTRY.register("stripped_peach_blossom_wood", () -> new StrippedPeachBlossomWoodBlock());
	public static final RegistryObject<Block> UNDER_ROCK = REGISTRY.register("under_rock", () -> new UnderRockBlock());
	public static final RegistryObject<Block> UNDER_ROCK_BRICKS = REGISTRY.register("under_rock_bricks", () -> new UnderRockBricksBlock());
	public static final RegistryObject<Block> UNDER_DIRT = REGISTRY.register("under_dirt", () -> new UnderDirtBlock());
	public static final RegistryObject<Block> UNDER_GRASS_BLOCK = REGISTRY.register("under_grass_block", () -> new UnderGrassBlockBlock());
	public static final RegistryObject<Block> SANGUINE_SAND = REGISTRY.register("sanguine_sand", () -> new SanguineSandBlock());
	public static final RegistryObject<Block> WUTIAO_GRASS = REGISTRY.register("wutiao_grass", () -> new WutiaoGrassBlock());
	public static final RegistryObject<Block> RONG_GRASS = REGISTRY.register("rong_grass", () -> new RongGrassBlock());
	public static final RegistryObject<Block> ZHUYU_GRASS = REGISTRY.register("zhuyu_grass", () -> new ZhuyuGrassBlock());
	public static final RegistryObject<Block> UNDER_IRON_ORE = REGISTRY.register("under_iron_ore", () -> new UnderIronOreBlock());
	public static final RegistryObject<Block> GUI_BASKET = REGISTRY.register("gui_basket", () -> new GuiBasketBlock());
	public static final RegistryObject<Block> UNDER_ROCK_GOLD_ORE = REGISTRY.register("under_rock_gold_ore", () -> new UnderRockGoldOreBlock());
	public static final RegistryObject<Block> GREEN_ROCK = REGISTRY.register("green_rock", () -> new GreenRockBlock());
	public static final RegistryObject<Block> SACRIFICIAL_TABLE = REGISTRY.register("sacrificial_table", () -> new SacrificialTableBlock());
	public static final RegistryObject<Block> WHITE_JIAN_GRASS_MAT = REGISTRY.register("white_jian_grass_mat", () -> new WhiteJianGrassMatBlock());
	public static final RegistryObject<Block> HOLLOW_MUD_BRICKS = REGISTRY.register("hollow_mud_bricks", () -> new HollowMudBricksBlock());
	public static final RegistryObject<Block> UNDER_ROCK_STAIRS = REGISTRY.register("under_rock_stairs", () -> new UnderRockStairsBlock());
	public static final RegistryObject<Block> UNDER_ROCK_SLAB = REGISTRY.register("under_rock_slab", () -> new UnderRockSlabsBlock());
	public static final RegistryObject<Block> UNDER_ROCK_FENCE = REGISTRY.register("under_rock_fence", () -> new UnderRockFenceBlock());
	public static final RegistryObject<Block> UNDER_ROCK_WALL = REGISTRY.register("under_rock_wall", () -> new UnderRockWallBlock());
	public static final RegistryObject<Block> UNDER_ROCK_BRICK_STAIRS = REGISTRY.register("under_rock_brick_stairs", () -> new UnderRockBrickStairsBlock());
	public static final RegistryObject<Block> UNDER_ROCK_BRICK_SLAB = REGISTRY.register("under_rock_brick_slab", () -> new UnderRockBrickSlabBlock());
	public static final RegistryObject<Block> UNDER_ROCK_BRICK_WALL = REGISTRY.register("under_rock_brick_wall", () -> new UnderRockBrickWallBlock());
	public static final RegistryObject<Block> UNDER_ROCK_BRICK_FENCE = REGISTRY.register("under_rock_brick_fence", () -> new UnderRockBrickFenceBlock());
	public static final RegistryObject<Block> WHITE_JIAN_GRASS_MAT_COVERED_SACRIFICIAL_TABLE = REGISTRY.register("white_jian_grass_mat_covered_sacrificial_table", () -> new WhiteJianGrassMatCoveredSacrificialTableBlock());
	public static final RegistryObject<Block> WHITE_JIAN_GRASS = REGISTRY.register("white_jian_grass", () -> new WhiteJianGrassBlock());
	public static final RegistryObject<Block> JADE_CONG = REGISTRY.register("jade_cong", () -> new JadeCongBlock());
	public static final RegistryObject<Block> JADE_CARVER = REGISTRY.register("jade_carver", () -> new JadeCarverBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE = REGISTRY.register("copper_zun_bottle", () -> new CopperZunBottleBlock());
	public static final RegistryObject<Block> UNDER_ROCK_QUARTZ_ORE = REGISTRY.register("under_rock_quartz_ore", () -> new UnderRockQuartzOreBlock());
	public static final RegistryObject<Block> UNDER_IRON_BLOCK = REGISTRY.register("under_iron_block", () -> new UnderIronBlockBlock());
	public static final RegistryObject<Block> THE_BLOOD_COPPER_BLOCK = REGISTRY.register("the_blood_copper_block", () -> new TheBloodCopperBlockBlock());
	public static final RegistryObject<Block> DEEPSLATE_JADE_ORE = REGISTRY.register("deepslate_jade_ore", () -> new DeepslateJadeOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_BLOOD_COPPER_ORE = REGISTRY.register("deepslate_blood_copper_ore", () -> new DeepslateBloodCopperOreBlock());
	public static final RegistryObject<Block> GREEN_JADE_BLOCK = REGISTRY.register("green_jade_block", () -> new GreenJadeBlockBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_BOYI = REGISTRY.register("copper_zun_bottle_boyi", () -> new CopperZunBottleBoshiBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_CHANGFU = REGISTRY.register("copper_zun_bottle_changfu", () -> new CopperZunBottleChangfuBlock());
	public static final RegistryObject<Block> SCARLET_THORNS = REGISTRY.register("scarlet_thorns", () -> new ScarletThornsBlock());
	public static final RegistryObject<Block> BLOODTHIRSTY_THORNS = REGISTRY.register("bloodthirsty_thorns", () -> new BloodthirstyThornsBlock());
	public static final RegistryObject<Block> THE_UNDER_PORTAL = REGISTRY.register("the_under_portal", () -> new TheUnderPortalBlock());
	public static final RegistryObject<Block> UNDER_GRASS = REGISTRY.register("under_grass", () -> new UnderGrassBlock());
	public static final RegistryObject<Block> COPPER_SMALL_DING = REGISTRY.register("copper_small_ding", () -> new CopperSmallDingBlock());
	public static final RegistryObject<Block> SANGUINE_GRASS = REGISTRY.register("sanguine_grass", () -> new SanguineGrassBlock());
	public static final RegistryObject<Block> UNDER_FLOWER = REGISTRY.register("under_flower", () -> new UnderFlowerBlock());
	public static final RegistryObject<Block> SANGUINE_FLOWER = REGISTRY.register("sanguine_flower", () -> new SanguineFlowerBlock());
	public static final RegistryObject<Block> SANGUINE_CACTUS = REGISTRY.register("sanguine_cactus", () -> new SanguineCactusBlock());
	public static final RegistryObject<Block> TING_ZHU = REGISTRY.register("ting_zhu", () -> new TingZhuBlock());
	public static final RegistryObject<Block> SANGUINE_SOIL = REGISTRY.register("sanguine_soil", () -> new SanguineSoilBlock());
	public static final RegistryObject<Block> COPPER_DOU = REGISTRY.register("copper_dou", () -> new CopperDouBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_CHICKEN = REGISTRY.register("copper_zun_bottle_chicken", () -> new CopperZunBottleChickenBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_PIGLIN = REGISTRY.register("copper_zun_bottle_piglin", () -> new CopperZunBottlePiglinBlock());
	public static final RegistryObject<Block> COPPER_GUI = REGISTRY.register("copper_gui", () -> new CopperGuiBlock());
	public static final RegistryObject<Block> COBBLED_GREEN_ROCK = REGISTRY.register("cobbled_green_rock", () -> new CobbledGreenRockBlock());
	public static final RegistryObject<Block> COPPER_DOU_LEI_MEAT_SAUCE = REGISTRY.register("copper_dou_lei_meat_sauce", () -> new CopperDouLeiMeatSauceBlock());
	public static final RegistryObject<Block> COPPER_DOU_BOYI_MEAT_SAUCE = REGISTRY.register("copper_dou_boyi_meat_sauce", () -> new CopperDouBoyiMeatSauceBlock());
	public static final RegistryObject<Block> COPPER_DOU_CHANGFU_CHICKEN_SAUCE = REGISTRY.register("copper_dou_changfu_chicken_sauce", () -> new CopperDouChangfuChickenSauceBlock());
	public static final RegistryObject<Block> YING_YANG_FLOWER = REGISTRY.register("ying_yang_flower", () -> new YingYangFlowerBlock());
	public static final RegistryObject<Block> UNDER_ORCHID = REGISTRY.register("under_orchid", () -> new UnderOrchidBlock());
	public static final RegistryObject<Block> BLOODTHIRSTY_CHRYSANTHEMUM = REGISTRY.register("bloodthirsty_chrysanthemum", () -> new BloodthirstyChrysanthemumBlock());
	public static final RegistryObject<Block> BRONZE_JUG = REGISTRY.register("bronze_jug", () -> new BronzeJugBlock());
	public static final RegistryObject<Block> BRONZE_XUAN = REGISTRY.register("bronze_xuan", () -> new BronzeXuanBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_LEI = REGISTRY.register("copper_zun_bottle_lei", () -> new CopperZunBottleLeiBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_LONG_CHI = REGISTRY.register("copper_zun_bottle_long_chi", () -> new CopperZunBottleLongChiBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_ZHENG = REGISTRY.register("copper_zun_bottle_zheng", () -> new CopperZunBottleZhengBlock());
	public static final RegistryObject<Block> CARNELIAN_ORE = REGISTRY.register("carnelian_ore", () -> new CarnelianOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_CARNELIAN_ORE = REGISTRY.register("deepslate_carnelian_ore", () -> new DeepslateCarnelianOreBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_ENDER_DRAGON = REGISTRY.register("copper_zun_bottle_ender_dragon", () -> new CopperZunBottleEnderDragonBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_SOUTH_MOUNTAINS_GOD = REGISTRY.register("copper_zun_bottle_south_mountains_god", () -> new CopperZunBottleSouthMountainsGodBlock());
	public static final RegistryObject<Block> COPPER_ZUN_BOTTLE_ZHI = REGISTRY.register("copper_zun_bottle_zhi", () -> new CopperZunBottleZhiBlock());
	public static final RegistryObject<Block> CARNELIAN_BLOCK = REGISTRY.register("carnelian_block", () -> new CarnelianBlockBlock());
	public static final RegistryObject<Block> FRUITFUL_YAN_LEAVES = REGISTRY.register("fruitful_yan_leaves", () -> new FruitfulYanLeavesBlock());
	public static final RegistryObject<Block> DIRT_WITH_RONG_GRASS_TUBERS = REGISTRY.register("dirt_with_rong_grass_tubers", () -> new DirtWithRongGrassTubersBlock());
	public static final RegistryObject<Block> XUN_LEAVES_BERRY = REGISTRY.register("xun_leaves_berry", () -> new XunLeavesBerryBlock());
	public static final RegistryObject<Block> FRUITFUL_SHATANG_LEAVES = REGISTRY.register("fruitful_shatang_leaves", () -> new FruitfulShatangLeavesBlock());
	public static final RegistryObject<Block> SANGUINE_GLASS = REGISTRY.register("sanguine_glass", () -> new SanguineGlassBlock());
	public static final RegistryObject<Block> BRONZE_DEVOURER_STATUE = REGISTRY.register("bronze_devourer_statue", () -> new BronzeDevourerStatueBlock());
	public static final RegistryObject<Block> SPOOKY_BRONZE_DEVOURER_STATUE = REGISTRY.register("spooky_bronze_devourer_statue", () -> new SpookyBronzeDevourerStatueBlock());
	public static final RegistryObject<Block> RED_LANTERN = REGISTRY.register("red_lantern", () -> new RedLanternBlock());
	public static final RegistryObject<Block> WHITE_LANTERN = REGISTRY.register("white_lantern", () -> new WhiteLanternBlock());
	public static final RegistryObject<Block> BLUE_LANTERN = REGISTRY.register("blue_lantern", () -> new BlueLanternBlock());
	public static final RegistryObject<Block> CYAN_LANTERN = REGISTRY.register("cyan_lantern", () -> new CyanLanternBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_LANTERN = REGISTRY.register("light_blue_lantern", () -> new LightBlueLanternBlock());
	public static final RegistryObject<Block> ORANGE_LANTERN = REGISTRY.register("orange_lantern", () -> new OrangeLanternBlock());
	public static final RegistryObject<Block> YELLOW_LANTERN = REGISTRY.register("yellow_lantern", () -> new YellowLanternBlock());
	public static final RegistryObject<Block> GREEN_LANTERN = REGISTRY.register("green_lantern", () -> new GreenLanternBlock());
	public static final RegistryObject<Block> LIME_LANTERN = REGISTRY.register("lime_lantern", () -> new LimeLanternBlock());
	public static final RegistryObject<Block> PURPLE_LANTERN = REGISTRY.register("purple_lantern", () -> new PurpleLanternBlock());
	public static final RegistryObject<Block> MAGENTA_LANTERN = REGISTRY.register("magenta_lantern", () -> new MagentaLanternBlock());
	public static final RegistryObject<Block> GRAY_LANTERN = REGISTRY.register("gray_lantern", () -> new GrayLanternBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_LANTERN = REGISTRY.register("light_gray_lantern", () -> new LightGrayLanternBlock());
	public static final RegistryObject<Block> BROWN_LANTERN = REGISTRY.register("brown_lantern", () -> new BrownLanternBlock());
	public static final RegistryObject<Block> BLACK_LANTERN = REGISTRY.register("black_lantern", () -> new BlackLanternBlock());
	public static final RegistryObject<Block> DRYING_BOARD = REGISTRY.register("drying_board", () -> new DryingBoardBlock());
	public static final RegistryObject<Block> PAPERMAKING_BOARD = REGISTRY.register("papermaking_board", () -> new PapermakingBoardBlock());
	public static final RegistryObject<Block> PINK_LANTERN = REGISTRY.register("pink_lantern", () -> new PinkLanternBlock());
	public static final RegistryObject<Block> SALINE_ORE = REGISTRY.register("saline_ore", () -> new SalineOreBlock());
	public static final RegistryObject<Block> SALT_BLCOK = REGISTRY.register("salt_blcok", () -> new SaltBlcokBlock());
	public static final RegistryObject<Block> COARSE_SALT_BLOCK = REGISTRY.register("coarse_salt_block", () -> new CoarseSaltBlockBlock());
	public static final RegistryObject<Block> WHITE_JIAN_GRASS_BLOCK = REGISTRY.register("white_jian_grass_block", () -> new WhiteJianGrassBlockBlock());

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			JianmeibambooBlock.blockColorLoad(event);
			HuangGuanLeavesBlock.blockColorLoad(event);
			PanLeavesBlock.blockColorLoad(event);
			LushGrassBlockBlock.blockColorLoad(event);
			UnderDirtBlock.blockColorLoad(event);
			WhiteJianGrassBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			JianmeibambooBlock.itemColorLoad(event);
			HuangGuanLeavesBlock.itemColorLoad(event);
			PanLeavesBlock.itemColorLoad(event);
			LushGrassBlockBlock.itemColorLoad(event);
			UnderDirtBlock.itemColorLoad(event);
			WhiteJianGrassBlock.itemColorLoad(event);
		}
	}
}
